name        'garethr-logstash'
version     '0.0.3'
source      'git://github.com/garethr/garethr-logstash.git'
author      'Gareth Rushgrove'
summary     'Module for managing logstash'
description 'logstash module based on puppet-logstash from Pål-Kristian Hamre'
license     'GPLv2'
dependency  'puppetlabs/java'
